### ISSUE TITLE
core dump して落ちることがある

### ISSUE THREAD

**Issue by verxirtam** [verxirtam/ATFViewer#31]
Thread 4 の~PathsVAO()で破棄したvectorに対して
thread 1 (PathsVAOの裏スレッド)でvaoへpush_back()をしようとしていた
->対策：
  ~PathsVAO()で、裏スレッドが完了するまで待機する

////////////////////////
// core dump時に起動中のスレッド
////////////////////////

```
(gdb) info thread
  Id   Target Id         Frame 
  14   Thread 0x2acc627af700 (LWP 3475) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  13   Thread 0x2acc625ae700 (LWP 3428) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  12   Thread 0x2acc623ad700 (LWP 3477) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  11   Thread 0x2acc621ac700 (LWP 3426) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  10   Thread 0x2acc629b0700 (LWP 3479) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  9    Thread 0x2acc617a7700 (LWP 3421) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  8    Thread 0x2acc61ba9700 (LWP 3478) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  7    Thread 0x2acc639cc700 (LWP 3434) pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  6    Thread 0x2acc637cb700 (LWP 3433) 0x00002acc5cf6bfdd in poll () at ../sysdeps/unix/syscall-template.S:81
  5    Thread 0x2acc619a8700 (LWP 3422) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  4    Thread 0x2acc5b169480 (LWP 3418) 0x00002acc5c23b65b in pthread_join (threadid=47057295009536, thread_return=0x0)
    at pthread_join.c:92
  3    Thread 0x2acc61daa700 (LWP 3424) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
  2    Thread 0x2acc61fab700 (LWP 3476) 0x00002acc5ca63b72 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
* 1    Thread 0x2acc615a6700 (LWP 3474) 0x000000000041e290 in __gnu_cxx::new_allocator<float>::construct<float, float>(float*, float&&)
    (this=0x683008 <ATFViewerMainGLSL::getInstance()::atfvm+1000>, __p=0x2accc1436ec8) at /usr/include/c++/4.8/ext/new_allocator.h:120
(gdb) 

```

////////////////////////
// thread 1
////////////////////////

->裏スレッドでinitData()実行中だった

```
(gdb) thread 1
[Switching to thread 1 (Thread 0x2acc615a6700 (LWP 3474))]
#0  0x000000000041e290 in __gnu_cxx::new_allocator<float>::construct<float, float>(float*, float&&) (
    this=0x683008 <ATFViewerMainGLSL::getInstance()::atfvm+1000>, __p=0x2accc1436ec8) at /usr/include/c++/4.8/ext/new_allocator.h:120
120             { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
(gdb) 

(gdb) bt
#0  0x000000000041e290 in __gnu_cxx::new_allocator<float>::construct<float, float>(float*, float&&) (
    this=0x683008 <ATFViewerMainGLSL::getInstance()::atfvm+1000>, __p=0x2accc1436ec8) at /usr/include/c++/4.8/ext/new_allocator.h:120

(中略)

#4  0x000000000041b361 in std::vector<float, std::allocator<float> >::push_back(float&&) (
    this=0x683008 <ATFViewerMainGLSL::getInstance()::atfvm+1000>, 
    __x=<unknown type in /home/daisuke/programs/ATFViewer/ATFViewer/src/glunittest, CU 0x72944, DIE 0x83e8c>)
    at /usr/include/c++/4.8/bits/stl_vector.h:920
#5  0x000000000043f2c9 in VAOLayoutPaths::initData (this=0x682fc4 <ATFViewerMainGLSL::getInstance()::atfvm+932>, input=..., data=...)
    at VAOLayoutPaths.cpp:37
#6  0x0000000000432f05 in VAOPositionBase<ShaderProgramPaths, VBODynamicBase<34962, float>, VBODynamicBase<34963, unsigned int>, VAOLayoutPaths>::initReady (this=0x682fc0 <ATFViewerMainGLSL::getInstance()::atfvm+928>, input=..., e=..., m=5) at VAOPositionBase.h:113
#7  0x00000000004329f7 in VAOPositionBaseDynamic<ShaderProgramPaths, VAOLayoutPaths>::initReady (
    this=0x682fc0 <ATFViewerMainGLSL::getInstance()::atfvm+928>, v=..., e=..., m=5) at VAOPositionBaseDynamic.h:47
#8  0x000000000042e93b in PathsVAO::initVAO (this=0x682ee8 <ATFViewerMainGLSL::getInstance()::atfvm+712>, path=..., v=...)
    at PathsVAO.cpp:262
#9  0x000000000042dd90 in PathsVAO::makePathsBuffer (this=0x682ee8 <ATFViewerMainGLSL::getInstance()::atfvm+712>, v=..., 
    position=TimeSeparation::next) at PathsVAO.cpp:55
#10 0x000000000042de0e in PathsVAO::__lambda4::operator() (__closure=0x1e15f40) at PathsVAO.cpp:68

(中略)

#32 0x00002acc5c23a184 in start_thread (arg=0x2acc615a6700) at pthread_create.c:312
#33 0x00002acc5cf7937d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 
```

////////////////////////
// thread 4
////////////////////////

-> ~PathsVAO()実行中で、PathsVAOは破棄されている最中だった。

```
(gdb) thread 4
[Switching to thread 4 (Thread 0x2acc5b169480 (LWP 3418))]
#0  0x00002acc5c23b65b in pthread_join (threadid=47057295009536, thread_return=0x0) at pthread_join.c:92
92      in pthread_join.c
(gdb) 
(gdb) 
#0  0x00002acc5c23b65b in pthread_join (threadid=47057295009536, thread_return=0x0) at pthread_join.c:92
#1  0x00002acc5c501837 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

(中略)

#21 0x000000000040797d in std::future<void>::~future (this=0x682f28 <ATFViewerMainGLSL::getInstance()::atfvm+776>, 
    __in_chrg=<optimized out>) at /usr/include/c++/4.8/future:726
#22 0x0000000000410e77 in PathsVAO::~PathsVAO (this=0x682ee8 <ATFViewerMainGLSL::getInstance()::atfvm+712>, __in_chrg=<optimized out>)
    at PathsVAO.h:38
#23 0x000000000041128d in ATFViewerMainGLSL::~ATFViewerMainGLSL (this=0x682c20 <ATFViewerMainGLSL::getInstance()::atfvm>, 
    __in_chrg=<optimized out>) at ATFViewerMainGLSL.h:40
#24 0x00002acc5cebb1a9 in __run_exit_handlers (status=0, listp=0x2acc5d23d6c8 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#25 0x00002acc5cebb1f5 in __GI_exit (status=<optimized out>) at exit.c:104
#26 0x00002acc5b880fb8 in glutMainLoopEvent () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#27 0x00002acc5b881065 in glutMainLoop () from /usr/lib/x86_64-linux-gnu/libglut.so.3
#28 0x000000000043fb36 in ATFViewerMainGLSL::execMainLoop (this=0x682c20 <ATFViewerMainGLSL::getInstance()::atfvm>)
    at ./ATFViewerMainGLSL.h:198
#29 0x000000000043f926 in main () at glunittest.cpp:173
(gdb) 
```

**Comment by verxirtam** [comment]
デストラクタで裏スレッドが完了するまで待機するため、
下記を追加した

``` c++
class PathsVAO
{
public:
    ~PathsVAO()
    {
        //メンバを破棄する前に裏スレッドが完了するまで待機する
        //(破棄したメンバを更新しないようにするため)
        futureMakeBuffer.wait();
    }
};
```
