### ISSUE TITLE
nvprof に失敗する

### ISSUE THREAD

**Issue by verxirtam** [verxirtam/ATFViewer#44]
nvprofを実行すると、下記を出力して落ちる。
`nvprof ./glunittest`の結果：

```
(中略)
copy mp to p start.
copy mp to p end.
getTrackDataFromDBParallel() end.
==2171== NVPROF is profiling process 2171, command: ./glunittest
==2171== Profiling application: ./glunittest
==2171== Profiling result:
No kernels were profiled.

==2171== API calls:
No API activities were profiled.
==2171== Warning: Some profiling data are not recorded. Make sure cudaProfilerStop() or cuProfilerStop() is called before application exit to flush profile data.
======== Error: Application received signal 139
```

cudaのサンプルでも同様だったので、cudaの問題と思われる。

**Comment by verxirtam** [comment]
`ulimit -c unlimited`して、coreを吐かせたら下記になった。
`libcuinj64.so`が直接の要因のようだが、back trace を見ると、
ディスプレイドライバの`/usr/lib/x86_64-linux-gnu/libcuda.so.1`がcudaのライブラリの間に入っている。
これ(`/usr/lib/nvidia-367`)がcudaドライバに対応できていない？

```
$ cuda-gdb ./glunittest core
NVIDIA (R) CUDA Debugger
7.5 release
Portions Copyright (C) 2007-2015 NVIDIA Corporation
GNU gdb (GDB) 7.6.2
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from ~/programs/ATFViewer/ATFViewer/src/glunittest...done.
[New LWP 2172]
[New LWP 2171]
[New LWP 2179]
[New LWP 2174]
[New LWP 2182]
[New LWP 2176]
[New LWP 2180]
[New LWP 2178]
[New LWP 2181]
[New LWP 2191]
[New LWP 2173]
[New LWP 2175]
[New LWP 2184]
[New LWP 2177]
[New LWP 2186]
[New LWP 2185]
[New LWP 2190]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./glunittest'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fa23ebc22dc in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
(cuda-gdb) bt
#0  0x00007fa23ebc22dc in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#1  0x00007fa23ebc14ab in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#2  0x00007fa23ea23fbf in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#3  0x00007fa23ea27439 in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#4  0x00007fa23f27fffc in cudbgApiDetach () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fa23f1d8a9e in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007fa23f1d8d80 in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#7  0x00007fa24fcaf52d in cudaGetExportTable () from /usr/local/cuda-7.5/lib64/libcudart.so.7.5
#8  0x00007fa24fca3ba0 in cudaGetExportTable () from /usr/local/cuda-7.5/lib64/libcudart.so.7.5
#9  0x00007fa24fcae796 in cudaGetExportTable () from /usr/local/cuda-7.5/lib64/libcudart.so.7.5
#10 0x00007fa24fcb2ed1 in cudaGetExportTable () from /usr/local/cuda-7.5/lib64/libcudart.so.7.5
#11 0x00007fa24fca645e in cudaGetExportTable () from /usr/local/cuda-7.5/lib64/libcudart.so.7.5
#12 0x00007fa24fc9a89e in cudaGetExportTable () from /usr/local/cuda-7.5/lib64/libcudart.so.7.5
#13 0x00007fa24fcc562c in cudaFree () from /usr/local/cuda-7.5/lib64/libcudart.so.7.5
#14 0x0000000000413b90 in DeviceMemory<unsigned int>::free (this=0x6a9078 <ATFViewerMainGLSL::getInstance()::atfvm+1080>) at DeviceSeq.cuh:110
#15 0x0000000000432e90 in DeviceMemory<unsigned int>::malloc (this=0x6a9078 <ATFViewerMainGLSL::getInstance()::atfvm+1080>, c=10840) at DeviceSeq.cuh:133
#16 0x000000000042eccf in PathsVAO::initVAO (this=0x6a8f08 <ATFViewerMainGLSL::getInstance()::atfvm+712>, path=..., db=..., time_start=1460641800, time_end=1460650200) at PathsVAO.cpp:318
#17 0x000000000042e032 in PathsVAO::makePathsBuffer (this=0x6a8f08 <ATFViewerMainGLSL::getInstance()::atfvm+712>, db=..., position=TimeSeparation::next) at PathsVAO.cpp:58
#18 0x000000000042e122 in PathsVAO::__lambda5::operator() (__closure=0xe590b0) at PathsVAO.cpp:83

(中略)

#41 0x00007fa24e0e537d in clone () from /lib/x86_64-linux-gnu/libc.so.6
(cuda-gdb) 

```

**Comment by verxirtam** [comment]
cudaのサンプルで実行した結果は上と同様
下記の通り：

```
~/NVIDIA_CUDA-7.5_Samples/0_Simple/matrixMul$ 
~/NVIDIA_CUDA-7.5_Samples/0_Simple/matrixMul$ cuda-gdb ./matrixMul core
NVIDIA (R) CUDA Debugger
7.5 release
Portions Copyright (C) 2007-2015 NVIDIA Corporation
GNU gdb (GDB) 7.6.2
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from ~/NVIDIA_CUDA-7.5_Samples/0_Simple/matrixMul/matrixMul...done.
[New LWP 1789]
[New LWP 1791]
[New LWP 1793]
[New LWP 1796]
[New LWP 1797]
[New LWP 1792]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./matrixMul'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007ff67304b2dc in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
(cuda-gdb) bt
#0  0x00007ff67304b2dc in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#1  0x00007ff67304a4ab in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#2  0x00007ff672eacfbf in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#3  0x00007ff672eb0439 in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#4  0x00007ff673957ffc in cudbgApiDetach () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007ff6738b0a9e in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007ff6738b0d80 in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#7  0x0000000000429f3d in cudart::contextState::loadCubin(bool*, void**) ()
#8  0x000000000041ccd0 in cudart::globalModule::loadIntoContext(cudart::contextState*) ()
#9  0x00000000004290a6 in cudart::contextState::applyChanges() ()
#10 0x000000000042d811 in cudart::contextStateManager::getRuntimeContextState(cudart::contextState**, bool) ()
#11 0x000000000042141c in cudart::doLazyInitContextState() ()
#12 0x000000000040db08 in cudart::cudaApiMalloc(void**, unsigned long) ()
#13 0x0000000000440daf in cudaMalloc ()
#14 0x0000000000402a48 in matrixMultiply (argc=1, argv=0x7fff3ca28178, block_size=32, dimsA=..., dimsB=...) at matrixMul.cu:160
#15 0x00000000004038a3 in main (argc=1, argv=0x7fff3ca28178) at matrixMul.cu:455
(cuda-gdb) q
~/NVIDIA_CUDA-7.5_Samples/0_Simple/matrixMul$ 
```

```
~/NVIDIA_CUDA-7.5_Samples/0_Simple/vectorAdd$ cuda-gdb ./vectorAdd core
NVIDIA (R) CUDA Debugger
7.5 release
Portions Copyright (C) 2007-2015 NVIDIA Corporation
GNU gdb (GDB) 7.6.2
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from ~/NVIDIA_CUDA-7.5_Samples/0_Simple/vectorAdd/vectorAdd...done.
[New LWP 2078]
[New LWP 2085]
[New LWP 2086]
[New LWP 2080]
[New LWP 2082]
[New LWP 2081]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./vectorAdd'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f5f104f42dc in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
(cuda-gdb) bt
#0  0x00007f5f104f42dc in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#1  0x00007f5f104f34ab in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#2  0x00007f5f10355fbf in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#3  0x00007f5f10359439 in InitializeInjection () from /usr/local/cuda-7.5/lib64/libcuinj64.so
#4  0x00007f5f11106ffc in cudbgApiDetach () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007f5f1105fa9e in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007f5f1105fd80 in cuMemGetAttribute_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#7  0x0000000000428e6d in cudart::contextState::loadCubin(bool*, void**) ()
#8  0x000000000041bc00 in cudart::globalModule::loadIntoContext(cudart::contextState*) ()
#9  0x0000000000427fd6 in cudart::contextState::applyChanges() ()
#10 0x000000000042c741 in cudart::contextStateManager::getRuntimeContextState(cudart::contextState**, bool) ()
#11 0x000000000042034c in cudart::doLazyInitContextState() ()
#12 0x000000000040ca38 in cudart::cudaApiMalloc(void**, unsigned long) ()
#13 0x000000000043fcdf in cudaMalloc ()
#14 0x0000000000402818 in main () at vectorAdd.cu:81
(cuda-gdb) 
```

**Comment by verxirtam** [comment]
cuda8.0RCに変えたらnvprofが使えるようになった。
cuda7.5がgtx1080のSM6.1に対応していないせいかも。

```
$ make gltest
nvprof --unified-memory-profiling off ./glunittest 2>&1 | tee -a glunittest.log
ATFViewerMainGLSL::init()

(中略)

getTrackDataFromDBParallel() end.
max{p[].pathPoint.size()} = 296
PathsVAO::makePathsBuffer() end.
glutMainLoop() finished.
==9151== Profiling application: ./glunittest
==9151== Profiling result:
Time(%)      Time     Calls       Avg       Min       Max  Name
 99.99%  1.45744s      3164  460.63us  212.99us  710.66us  PathsVAO_updateDeviceDataCUDA(float, float, float*, unsigned int*, unsigned int*)
  0.00%  70.944us        10  7.0940us  2.0480us  12.832us  [CUDA memcpy HtoD]
  0.00%  8.6720us        10     867ns     608ns  1.2480us  [CUDA memcpy DtoH]

==9151== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 78.97%  1.61774s      3164  511.29us  194.06us  1.6929ms  cudaThreadSynchronize
 11.26%  230.72ms        10  23.072ms  22.121us  229.99ms  cudaFree
  5.82%  119.32ms      3164  37.712us  20.277us  268.19us  cudaLaunch
  2.40%  49.118ms        14  3.5084ms  131.68us  14.299ms  cudaGraphicsUnregisterResource
  0.56%  11.504ms        18  639.09us  286.65us  3.2715ms  cudaGraphicsGLRegisterBuffer
  0.38%  7.7868ms     15820     492ns     192ns  18.472us  cudaSetupArgument
  0.37%  7.4842ms      3164  2.3650us  1.2500us  9.9230us  cudaConfigureCall
  0.09%  1.8079ms        10  180.79us  16.057us  431.58us  cudaMalloc
  0.08%  1.6875ms        20  84.372us  27.688us  893.77us  cudaMemcpy
  0.03%  541.36us        18  30.075us  19.915us  50.574us  cudaGraphicsMapResources
  0.02%  322.33us        90  3.5810us     182ns  118.40us  cuDeviceGetAttribute
  0.01%  262.94us         1  262.94us  262.94us  262.94us  cuDeviceTotalMem
  0.01%  238.24us        18  13.235us  9.8960us  18.376us  cudaGraphicsUnmapResources
  0.00%  50.694us         1  50.694us  50.694us  50.694us  cuDeviceGetName
  0.00%  45.177us        18  2.5090us  1.6620us  5.7390us  cudaGraphicsResourceGetMappedPointer
  0.00%  3.4270us         2  1.7130us     440ns  2.9870us  cuDeviceGetCount
  0.00%     763ns         2     381ns     247ns     516ns  cuDeviceGet
if [ -f core ]; then banner core dumped!;fi
gprof glunittest | ~/tools/gprof2dot/gprof2dot.py | dot -Tpng -o gprof_call_graph_glunittest.png
$ 

```

ただし、オプション「 --unified-memory-profiling off」を付けないと、
「Error: unified memory profiling failed.」と出て終了してしまう。理由がわからない。

```
$ nvprof ./glunittest
ATFViewerMainGLSL::init()

(中略) 

copy mp to p end.
getTrackDataFromDBParallel() end.
==9236== NVPROF is profiling process 9236, command: ./glunittest
======== Error: unified memory profiling failed.
$ 
```

サンプルのmatrixMulでも起こるのでcudaの設定の問題と思われる。

```
$ nvprof ./matrixMul
[Matrix Multiply Using CUDA] - Starting...
==9472== NVPROF is profiling process 9472, command: ./matrixMul
GPU Device 0: "GeForce GTX 1080" with compute capability 6.1

MatrixA(320,320), MatrixB(640,320)
======== Error: unified memory profiling failed.
$ 
```

**Comment by verxirtam** [comment]
CUDA８ がリリースされた…。
知ってれば待っていたのに…。
https://devblogs.nvidia.com/parallelforall/cuda-8-features-revealed/
CUDA8のインストーラに付属しているnvidiaドライバは最新のはずなので、上記が解消するかもしれない。

**Comment by verxirtam** [comment]
c31a79f までに CUDA8 に更新した。
nvprofはオプション無しで実行可能になった。
